"""Render the three `.env` files from wizard answers + generated secrets.

Pure functions (answers in, text out) so they're golden-testable. The shape
mirrors each service's `.env.example` — that file is the public contract the
wizard consumes (ADR-005): a new provisioning-relevant variable there means
updating these renderers in the same release.
"""

from chasqui.secrets_gen import GeneratedSecrets
from chasqui.wizard import EMBEDDING_PROVIDERS, LLM_PROVIDERS, Answers

PLACEHOLDER = "fill-me"


def _api_key_lines(a: Answers) -> list[str]:
    """One line per credential the chosen providers need (LLM + embeddings)."""
    lines: list[str] = []
    seen: set[str] = set()
    llm_var = LLM_PROVIDERS.get(a.llm_provider, (None, None))[1]
    emb_var = EMBEDDING_PROVIDERS.get(a.embedding_provider, (None, None))[1]
    if llm_var:
        lines.append(f"{llm_var}={a.llm_api_key or PLACEHOLDER}")
        seen.add(llm_var)
    if emb_var and emb_var not in seen:
        lines.append(f"{emb_var}={a.embedding_api_key or PLACEHOLDER}")
        seen.add(emb_var)
    if a.llm_provider == "ollama" or a.embedding_provider == "ollama":
        lines.append(f"OLLAMA_BASE_URL={a.ollama_base_url}")
    return lines


def render_core_env(a: Answers, s: GeneratedSecrets) -> str:
    blocks: list[str] = []

    blocks.append(
        "# App\n"
        f"APP_NAME={a.project_name}\n"
        "DEBUG=true\n"
        "# API port (make dev honors it)\n"
        f"PORT={a.core_port}"
    )

    blocks.append(
        "# Database (pgvector required — ADR-002)\n"
        f"POSTGRES_HOST={a.pg_host}\n"
        f"POSTGRES_PORT={a.pg_port}\n"
        f"POSTGRES_USER={a.pg_user}\n"
        f"POSTGRES_PASSWORD={a.pg_password}\n"
        f"POSTGRES_DB={a.db_name}"
    )

    blocks.append(
        "# JWT (admin authentication) — generated by chasqui new\n"
        f"JWT_SECRET_KEY={s.jwt_secret_key}\n"
        "JWT_ALGORITHM=HS256\n"
        "ACCESS_TOKEN_EXPIRE_MINUTES=30\n"
        "REFRESH_TOKEN_EXPIRE_DAYS=7"
    )

    blocks.append(
        "# CORS\n"
        f"CORS_ORIGINS=http://localhost:{a.admin_port},http://localhost:3000\n"
        "CORS_ALLOW_CREDENTIALS=true"
    )

    blocks.append(
        "# Shared secret the WhatsApp gateway uses to call /ingest\n"
        "# (same value lives in whatsapp/.env — generated by chasqui new)\n"
        f"INTERNAL_API_KEY={s.internal_api_key}"
    )

    llm = (
        "# LLM — provider/model swappable any time, applies on the next message\n"
        f"LLM_PROVIDER={a.llm_provider}\n"
        f"LLM_MODEL={a.llm_model}\n"
        "LLM_TEMPERATURE=0.7"
    )
    key_lines = _api_key_lines(a)
    if key_lines:
        llm += "\n" + "\n".join(key_lines)
    blocks.append(llm)

    blocks.append(
        "# Embeddings — EMBEDDING_DIM is PROVISION-TIME (ADR-001): baked into\n"
        "# the schema on the first migrate; changing it later = column\n"
        "# migration + re-embed.\n"
        f"EMBEDDING_PROVIDER={a.embedding_provider}\n"
        f"EMBEDDING_MODEL={a.embedding_model}\n"
        f"EMBEDDING_DIM={a.embedding_dim}"
    )

    if a.storage_bucket:
        storage = "# Media storage (ADR-003) — S3-compatible via boto3\n"
        if a.storage_endpoint_url:
            storage += f"STORAGE_ENDPOINT_URL={a.storage_endpoint_url}\n"
        storage += (
            f"STORAGE_BUCKET={a.storage_bucket}\n"
            f"STORAGE_ACCESS_KEY={a.storage_access_key}\n"
            f"STORAGE_SECRET_KEY={a.storage_secret_key}"
        )
        if a.storage_region:
            storage += f"\nSTORAGE_REGION={a.storage_region}"
        blocks.append(storage)
    else:
        blocks.append(
            "# Media storage (ADR-003) — OPTIONAL; unset = inbound media is\n"
            "# processed in-turn but not persisted. See core/.env.example.\n"
            "# STORAGE_ENDPOINT_URL=\n"
            "# STORAGE_BUCKET=\n"
            "# STORAGE_ACCESS_KEY=\n"
            "# STORAGE_SECRET_KEY=\n"
            "# STORAGE_REGION="
        )

    send_urls = ["# Canonical outbound seam (ADR-004) — where operator replies go"]
    if "whatsapp" in a.channels:
        send_urls.append(
            f"CHANNEL_WHATSAPP_SEND_URL=http://localhost:{a.gateway_port}/send"
        )
    if "telegram" in a.channels:
        send_urls.append(
            f"CHANNEL_TELEGRAM_SEND_URL=http://localhost:{a.telegram_port}/send"
        )
    blocks.append("\n".join(send_urls))

    notify_lines: list[str] = []
    if a.notify_webhook_url:
        notify_lines.append(f"NOTIFY_WEBHOOK_URL={a.notify_webhook_url}")
    if a.smtp_host:
        notify_lines += [
            f"SMTP_HOST={a.smtp_host}",
            f"SMTP_PORT={a.smtp_port}",
            f"SMTP_USER={a.smtp_user}",
            f"SMTP_PASSWORD={a.smtp_password}",
            f"SMTP_FROM={a.smtp_from}",
            f"NOTIFY_EMAIL_TO={a.notify_email_to}",
        ]
    if notify_lines:
        blocks.append(
            "# Handoff notifications (ADR-004) — best-effort\n"
            + "\n".join(notify_lines)
        )
    else:
        blocks.append(
            "# Handoff notifications (ADR-004) — OPTIONAL, see core/.env.example\n"
            "# NOTIFY_WEBHOOK_URL=\n"
            "# SMTP_HOST=\n"
            "# SMTP_PORT=587\n"
            "# SMTP_USER=\n"
            "# SMTP_PASSWORD=\n"
            "# SMTP_FROM=\n"
            "# NOTIFY_EMAIL_TO="
        )

    if a.stt_provider:
        blocks.append(
            "# Speech-to-text fallback (ADR-010) — transcribe voice notes when the\n"
            "# LLM lacks native audio. Key is SEPARATE from the LLM key.\n"
            f"STT_PROVIDER={a.stt_provider}\n"
            f"STT_MODEL={a.stt_model}\n"
            f"STT_API_KEY={a.stt_api_key}"
        )
    else:
        blocks.append(
            "# Speech-to-text fallback (ADR-010) — OPTIONAL; unset = the agent asks\n"
            "# the user to type a voice note when the LLM can't hear. Groq default\n"
            "# (native OGG/Opus). See core/.env.example.\n"
            "# STT_PROVIDER=groq\n"
            "# STT_MODEL=whisper-large-v3-turbo\n"
            "# STT_API_KEY="
        )

    blocks.append(
        "# Agent turn\n"
        "HISTORY_LIMIT=20\n"
        "# Sent verbatim to the end user when a turn fails (your users' language)\n"
        f"FALLBACK_REPLY={a.fallback_reply}"
    )

    return "\n\n".join(blocks) + "\n"


def render_whatsapp_env(a: Answers, s: GeneratedSecrets) -> str:
    wa = lambda v: v or PLACEHOLDER  # noqa: E731
    return (
        "# Server\n"
        f"PORT={a.gateway_port}\n"
        "\n"
        "# WhatsApp Business API\n"
        "# WA_PHONE_ID is REQUIRED for operator replies (POST /send, ADR-004)\n"
        f"WA_PHONE_ID={wa(a.wa_phone_id)}\n"
        f"WA_TOKEN={wa(a.wa_token)}\n"
        "# Paste this verify token into the Meta webhook configuration:\n"
        f"WA_VERIFY_TOKEN={s.wa_verify_token}\n"
        f"WA_APP_ID={wa(a.wa_app_id)}\n"
        f"WA_APP_SECRET={wa(a.wa_app_secret)}\n"
        f"WA_WABA_ID={wa(a.wa_waba_id)}\n"
        "# Dev only (ngrok); in production configure the webhook in Meta Business Suite\n"
        "# WA_CALLBACK_URL=https://your-ngrok-url.ngrok.io\n"
        "\n"
        "# Chasqui core\n"
        f"CORE_URL=http://localhost:{a.core_port}\n"
        "# Same value as core/.env (generated by chasqui new)\n"
        f"INTERNAL_API_KEY={s.internal_api_key}\n"
        "\n"
        "# Sentry (optional)\n"
        "SENTRY_DSN=\n"
    )


def render_telegram_env(a: Answers, s: GeneratedSecrets) -> str:
    return (
        "# Server\n"
        f"PORT={a.telegram_port}\n"
        "\n"
        "# Telegram Bot API — get a token from @BotFather\n"
        f"TELEGRAM_BOT_TOKEN={a.tg_bot_token or PLACEHOLDER}\n"
        "# Telegram echoes this in the X-Telegram-Bot-Api-Secret-Token header\n"
        f"TELEGRAM_WEBHOOK_SECRET={s.telegram_webhook_secret}\n"
        "# Dev only (ngrok); the gateway registers the webhook on startup\n"
        "# TELEGRAM_WEBHOOK_URL=https://your-ngrok-url.ngrok.io/webhook\n"
        "\n"
        "# Chasqui core\n"
        f"CORE_URL=http://localhost:{a.core_port}\n"
        "# Same value as core/.env (generated by chasqui new)\n"
        f"INTERNAL_API_KEY={s.internal_api_key}\n"
        "\n"
        "# Sentry (optional)\n"
        "SENTRY_DSN=\n"
    )


def render_admin_env(a: Answers) -> str:
    return (
        "# API Base URL\n"
        f"VITE_API_BASE_URL=http://localhost:{a.core_port}\n"
        "\n"
        "# Default UI locale (en | es) — the header switcher overrides it per browser\n"
        f"VITE_DEFAULT_LOCALE={a.locale}\n"
        "\n"
        "# Dev server port\n"
        f"VITE_PORT={a.admin_port}\n"
    )
